server:
  port: 8080

springdoc:
  api-docs:
    path: /rb-student-openapi
  swagger-ui:
    path: /rakbank/api/student/swagger-ui.html

spring:
  datasource:
    url: jdbc:h2:mem:studentdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
